# Generated by Django 4.1.3 on 2022-12-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tahu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(blank=True)),
                ('judul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.habib')),
            ],
        ),
    ]
